### ISSUE TITLE
Crashes at automatic cleanup

### ISSUE THREAD

**Issue by TException** [CodeDead/MemPlus#9]
Hy,
First of all thank you for this awesome app!

When i click manually to cleanup memory it works fine, but the automatic one is always crashes.
(The app simply exit, no error message shown)
Version:1.3.2.0

![image](https://user-images.githubusercontent.com/2140697/52823777-749ae480-30b6-11e9-96f4-d53e451fa64a.png)

**Comment by CodeDead** [comment]
Thank you for pointing that out and apologies for the delay. We have identified an issue with that feature and a fix is on the way!

**Comment by CodeDead** [comment]
**Cause (only when called from the timer due to the nature of their implementation / threading):**
https://github.com/CodeDead/MemPlus/blob/master/MemPlus/Business/RAM/RamController.cs#L284

**Solution:**
user32.dll API call [OpenClipboard](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-openclipboard) followed by [EmptyClipboard](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-emptyclipboard) and lastly [CloseClipboard](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-closeclipboard)

**Comment by CodeDead** [comment]
This bug has been fixed in the following commit:
https://github.com/CodeDead/MemPlus/commit/d7491011352bf6de3f1e0db07995f00edb409f51

The fix will be publicly available in version 1.4. Thank you for reporting this issue!
